version: "3"
services:
  api:
    build: ./apps/api
    volumes:
      - ./apps/api:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres